name: Docker CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2

      - name: Checking out repository code update
        run: |
          cat ./apps/web/src/app/page.tsx

      - name: Launch Docker Compose Services
        run: |
          sudo docker compose up --build -d
